yeoman/generator

lib/actions/actions.js

Made three grammar changes to help improve the readability of the doc.

Grammar Changes

---

gulpfile.js

This will also make TravisCI returns an error when a test fails.

Make gulp test task fails when some test fails

---

lib/actions/install.js

Changed order of installDependencies to run npm -> bower

---

lib/actions/fetch.js
test/fetch.js

fixes #794, fetch.extract downloading an empty tarball

---

lib/base.js

./base.js - comment syntax error

---

package.json

Fixes https://github.com/yeoman/generator/issues/831.

Update `cross-spawn` dependency

---

package.json

inquirer 0.9.0 fixed the issue [inputs repeating question when input wraps'](https://github.com/SBoudrias/Inquirer.js/issues/214)

Update inquirer to 0.9.0

---

package.json

Fix for Node < 4, downgrade read-chunk

---

lib/base.js
lib/util/prompt-suggestion.js
test/prompt-suggestion.js

This will save user answers to local storage as well. Then next time you execute yo it will first try to find global storage then local and override with local prompts.
This is very useful when I produce multiple projects (components) using the same generator. Then next time I want to update I wont be answering same questions again.

Save current config to .yo-rc.json

---

lib/index.js

Per documentation here
https://github.com/SBoudrias/mem-fs-editor#writefilepath-contents

Fix fs documentation

---

lib/actions/install.js
test/install.js

Resolves #1014 
Let me know what you would like changed! :smile:

New: option shorthand on installDependencies method

---

lib/actions/install.js
test/install.js

This PR addresses #906 by logging a failed or skipped install command, so that the user can perform it manually.

Output skipped or failed install commands

---

lib/actions/install.js
lib/index.js
test/base.js
test/install.js

scheduleInstallTask should fail incase installer fails and --force-install option set Fix #1080

scheduleInstallTask should fail incase installer fails and --force-install option set Fix #1080

---

lib/actions/install.js
lib/index.js
test/base.js
test/install.js

force-install is not used properly #1082

force-install is not used properly #1082

---

lib/index.js
test/base.js

This allows generators getter to use 'this' variable.

Call getter binding the generator.

---

lib/index.js

This behaviour is likely as in the yeoman/environments Generator factory 
https://github.com/yeoman/environment/blob/v2.5.0/lib/environment.js#L425

Support importing Generators with default exports

---

lib/index.js

Set runningState on generator.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Add issues templates with label 'needs triage' applied.
https://github.com/yeoman/generator/issues/1143

Add issues templates.

---

lib/util/storage.js
test/storage.js

Small improvements.
- Add new line to yo-rc.json end.
- Allow store to be used without a namespace.

Improvements.

---

lib/index.js
test/base.js

Otherwise there is no way to get the composed instance

Add returnNewGenerator option to composeWith

---

.travis.yml
package.json

- Upgraded Nodejs version in package.json
- Upgraded Nodejs versions for CI
Close #1159

Drop support for Node v8

---

lib/index.js
test/generators.js

Fixes https://github.com/yeoman/generator/issues/1182

Fix running yeoman-generator alone without a full featured environment

---

lib/index.js

Fixes https://github.com/yeoman/generator/issues/1189

Move grouped-queue require

---

lib/index.js

Fixes https://github.com/yeoman/generator/issues/1192

Add missing parameter to catch

---

lib/index.js
lib/util/conflicter.js
test/base.js
test/conflicter.js

Fixes https://github.com/yeoman/generator/issues/1202

Implement conflicter predefined status

---

lib/actions/fs.js
package-lock.json
package.json
test/fs.js

Requires an updated version of mem-fs-editor.

Pass the generator as context for ejs.render by default.

---

.github/workflows/gh_pages.yml
lib/actions/install.js
lib/actions/package-json.js
lib/index.js
package.json

Related to https://github.com/yeoman/generator/issues/1294.

Fix jsdoc for install/package-json actions.

---

lib/index.js
test/base.js

allows to change the default value by changing the answers object.

make prompt default value dynamic

---

src/actions/lifecycle.ts
test/base.test.ts

Fixes https://github.com/yeoman/generator/issues/1579

fix: keep resolved as absolute path

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/gh_pages.yml
.github/workflows/integration.yml
.github/workflows/lock-maintenance.yml
.github/workflows/scorecards.yml
.github/workflows/stale.yml

This PR included all the changes from #1600 and some improvements (7480dab0910b6b38868cf72f2dd0f1aded6404a2)
- Related: https://github.com/yeoman/.github/issues/1
- Closes #1600

ci: apply security best practices

---

src/actions/lifecycle.ts
test/base.test.ts

fix: executeTask should fallback to priority's args

---

package-lock.json
package.json
src/actions/spawn-command.ts
test/fixtures/generator-mocha/package-lock.json
test/fixtures/options-generator/package-lock.json
test/spawn-command.test.ts

chore!: update execa to v9

---

package-lock.json
package.json

chore: bump environment

---

package.json
src/generator.ts
test/generators.test.ts

Implements generator side shared context.
Depends on https://github.com/yeoman/environment/pull/601

feat: add getContextData

---

src/generator.ts
test/generators.test.ts

feat: add custon context to getContextData and implement setContextData

---

src/generator.ts
test/generators.test.ts

feat: replace setContextData with improved getContextData api

---

package-lock.json
package.json
src/actions/fs.ts
src/generator.ts
src/index.ts
src/types.d.ts
src/util/prompt-suggestion.ts
src/util/storage.ts

feat: add generics to Storage

---

src/util/storage.ts

feat: improve createStorage type

---

tsconfig.json

chore: tsconfig adjusts

---

src/actions/lifecycle.ts

chore: make composeWith optionally async.

---

package-lock.json
package.json

fix: move @types/debug to prod dependencies
