lib/base.js, lib/util/conflicter.js
detect-conflict dependency handles buffers properly, so this toString() call is not required anymore and cause false positive on conflicter.
Close #717
=> Fix conflicter by removing toString() call

lib/actions/actions.js, package.json
This avoid reading the file twice, and also drop one dependency when #737 is merged.
compared to [isbinaryfile](https://github.com/gjtorikian/isBinaryFile), [istextorbinary](https://github.com/bevry/istextorbinary) can handles a `Buffer` as input instead of filename.
=> Replace isbinaryfile with istextorbinary

lib/test/helpers.js, lib/test/run-context.js, test/run-context.js
As discussed on issue #742 I created a PR:
Here's what I've done so far:
write unit test for `withLocalConfig()` method
write a `mockLocalConfig()` function, that uses the generator's store's `default()` method to provide the config. This seemed an easy way to implement it, however I'm not sure whether it's a good idea to do so.
extend the `RunContext` constructor, its `_run()` method and added a `withLocalConfig()` method to put everything together.
Notice how `helper.mockLocalConfig()`only gets called when `withLocalConfig()` was called? I needed to restrict this, since otherwise one of the tests would try to create a `.yo-rc.json` in `/` (root directory) and obviously would fail (I don't know why this happens though...).
Please let me know what you think.
=> PR on issue #742 withLocalConfig - basic tests & implementation

package.json
Currently yeoman expects jsdoc to be present on the user's machine.  This adds the dependency so a separate install isn't necessary to run "npm run-script doc".
=> adding jsdoc dependency

lib/base.js, test/base.js
This adds the possibility of writing generators with ES2015 class
syntax. Fixes #767.
=> Allow the Base generator to find non-enumerable methods

lib/base.js
When I call `this.welcome()` in my generator's `initializing` function, always get a TypeError: Object has no method 'apply'.
And I found the bug in `util/deprecate.js` file, `deprecate.object` always call `deprecate` function without provide a function parameter.
=> Fix deprecate bug

lib/util/prompt-suggestion.js, test/prompt-suggestion.js
When answering to a question with a falsy value (like `false` or `0`), it wasn't store in the global yo json.
=> Fix falsy answers not stored

jsdoc.json
Partially addresses #858. Jsdoc still needs to be run and copied into the gh-pages branch.
=> Update jsdoc to include readme.md for home page.

lib/test/helpers.js
=> Fix typo in JSDoc example

jsdoc.json
There is no index.js in the repo root anymore.
=> Remove non-existent file from JSDoc config

gulpfile.js, lib/base.js, test/base.js
- Ensure the callback in runAsync never throw error.
- The unit test action#bulkDirectory() sometimes fail because of mocha timeout. So I set it to 3000ms.
Refer to #921
=> Fix the error thrown from generator is swallowed

package.json
path-exists 3.0.0 uses ES6 stuff that older Node versions don't like
=> Fix for Node < 4, downgrade path-exists

lib/actions/install.js
This PR chains together multiple install commands (e.g., `bower install && npm install`) with a double ampersand instead of a single ampersand. See issue https://github.com/yeoman/generator/issues/943 for more context around this.
=> Chain install commands with double ampersand

test/deprecate.js
Usage of stub for console.log affects the output of test reporter (it is not restored before the reporter logs the result of the test). Look at the deprecate test-suite. It's output is
```
deprecate()
.object()
.property()
```
For example, you cannot see that there is `log a message` test that passed.
=> Usage of stub consumes part of test reporter output

lib/actions/install.js
Closes #871
A `bower.json` and a `package.json` without any dependencies defined.
Using the following install method within a dummy generator:
```js
install: function () {
this.npmInstall(['lodash'], { save: true });
this.bowerInstall('lodash', { save: true });
}
```
`bower install` fails silently by generating the following output:
`bower install` fails properly with the following error message:
Using callbacks for installation within a dummy generator:
```js
install: function () {
this.npmInstall(['lodash'], { save: true }, function (callbackParam) {
console.log('npm callbackParam=', callbackParam);
});
this.bowerInstall('lodash', { save: true }, function (callbackParam) {
console.log('bower callbackParam=', callbackParam);
});
}
```
`bower install` fails with printing the raw error: …
=> Fix error handling for non installed install methods

lib/index.js
Fixes #886
Changes deprecation message when using 
```
yeoman.generators.NamedBase.extend()
```
**Before:**
**After:**
---
Correct deprecation messages remain untouched.
```
yeoman.generators.Base.extend()
```
```
yeoman.NamedBase.extend()
```
=> Fix deprecation message for using `NamedBase`

package.json
It’s already set up to use the readme for JSDoc HTML file over here:
https://github.com/yeoman/generator/blob/master/jsdoc.json#L3
Works fine without that duplicate in package.json 😘
=> Remove duplicated reference of the readme for docs

.travis.yml, deploy.sh
Closes #673
Closes yeoman/Hackathons#9
This generates and deploys docs with every published tag to the `gh-pages` branch 🎉 
This PR is an adoption of a working proof of concept which is a sharable solution composed of:
+ a few additions to the existing travis config
+ a bash script
See https://github.com/mischah/test-auto-publishing-gh-pages
Its easy adaptable to fix yeoman/environment#9 as well (just by changing a few values in `.travis.yml`).
But to get that running over here someone with push access to this repo has to enable push access for Travis by:
1. creating a Github OAuth token
2. encrypting that OAuth token for use with Travis
These steps are described within the comments of the updated `.travis.yml`:
https://github.com/mischah/generator/blob/automate-publishing-docs/.travis.yml …
=> Setup Travis deployment of generated docs to gh-pages

lib/actions/install.js, test/base.js, test/install.js
Hi,
I worked with @hemanth on a little PR to add a default cache, very long (Infinite) by default.
This has the benefit of drastically speeding up npm installs, anytime a given package@version has already been installed.
It would work the same on the first run, and feel very fast on subsequent runs.
Also adding a little patch to have tests pass on win32 platform (LF issue)
cc @addyosmani
=> npm cache by default

.travis.yml, deploy.sh, jsdoc.json
Post treatment of #971
The changes of this PR will prevent multiple commits of docs in gh-pages branch when pushing a new tag.
It could be easier. But Travis doesn’t offer something like a [single `after_success` callback after *all* builds](https://github.com/travis-ci/travis-ci/issues/929).
So I first checked if there are changes between commits: 
https://github.com/yeoman/generator/commit/f7df1d7daf064a2ae048c437d38a091c76dc8a05#diff-60254338249f657a0a83f98258a56bfeR51
Sadly this approach alone didn’t worked out. Because the default JSDoc template renders a timestamp into the footer.
See: https://github.com/yeoman/generator/commit/1475d16fc4fa34bd1334ae3764c67788c6a56e05
So I disabled the output of the date/time in the footer and configured JSDoc to render the package name and version …
=> Prevent multiple commits of docs in gh-pages branch

.travis.yml, deploy.sh, jsdoc.json
Simplified the prevention of multiple commits of docs in `gh-pages` branch as discussed in #975
=> Only build and deploy docs on a specific node version

jsdoc.json, package.json
So we have a search in the API docs as requested in yeoman/yeoman#1485
Let me quote myself from yeoman/yeoman#1485:
> I did some research regarding JSDoc templates and tried a few.
> That made me sad. There are just 3 with search functionality. And just one of them makes sense to use for the Yeoman docs because it’s looks good, has a good UX and offers all the features of the default template.
>
> The good news: The one is a extremely new kid on the block (first release 4 days ago) but its super awesome.
The docs will look like this:
=> Switch JSDoc template

jsdoc.json
Takes the version number from `package.json` and prints it to the left column of the docs.
=> Add version number to generated docs

lib/index.js, test/base.js
This PR propose an elegant solution to issue #947.
By exposing the directory where the generator was executed, we give the opportunity to subgenerators to scaffold into the current folder instead of the project folder.
Tests have been implemented. I hope the name `contextRoot` for the property is OK to everyone.
=> Expose the directory where the generator is being executed

lib/index.js
There was a `generator.Base.extend` in the docs.
Guess that should be ES6 too, right?
=> Update example for docs

lib/index.js, test/base.js
Got to add and fix tests. But here's a first draft to tackle the bug.
=> Fix undefined boolean options - Fix #988

lib/util/binary-diff.js, test/conflicter.js
Makes `null` content (file deletion):
1. not identify as binary (so default diff style is nicer)
2. not break binary diff if it is
Addresses regression(?) of #950
=> Don't die on diffing file deletions (again)

lib/util/prompt-suggestion.js, test/prompt-suggestion.js
This is a bit odd as it introduces a difference in the way Yeoman handles applying storage defaults, however it appears to be the safest and least intrusive way to honor the Inquirer API.
In the future, we could consider pre-filling prompts on a question-by-question basis so that we can invoke the `question.choices` function with the previous answers.
=> fix: Do not apply user defaults when question.choices is a function. Fixes #1051.

lib/actions/help.js, test/base.js
yeoman/yeoman.github.io/issues/750
I've created small generator to test correct order of arguments and options:
```js
constructor(args, opts) {
super(args, opts);
this.argument('a', { type: String, required: false });
this.argument('b', { type: String, required: false });
this.option('c', { type: String });
this.option('d', { type: Boolean });
this.log({
a: this.options.a,
b: this.options.b,
c: this.options.c,
d: this.options.d
});
}
```
And there is some output:
```sh
$ yo order
{ a: undefined, b: undefined, c: undefined, d: undefined }
$ yo order foo bar --c --d
{ a: 'foo', b: 'bar', c: 'true', d: true }
$ yo order foo bar --c=baz --d=qux
{ a: 'foo', b: 'bar', c: 'baz', d: true }
```
Seems to all be ok. Even if we change order:
```sh
$ yo order foo --c=baz bar --d=qux
{ a: 'foo', b: …
```
=> Change options and args order

test/base.js
.gitattributes makes all .js files use LF as EOL. This change makes
the tests pass on Windows.
=> Fix test on Windows

lib/actions/install.js, test/install.js
With the current behavior, if a generator tries to do something like this:
```js
this.npmInstall();
this.npmInstall(null, null, {cwd: this.destinationPath('some-other-path')});
```
the second call is ignored.
If we want to create a full-stack generator (like I'm doing) that needs to run `npm install` in multiple paths, we are stuck.
This PR takes in account the unicity of the `spawnOptions` parameter to dedupe the install calls, fixing the current behavior.
=> Run separate install process if spawnOptions differs

lib/index.js
This is useful for generators that uses generators from multiple packages.
=> Add rootName parameter to _getStorage

lib/index.js, test/base.js
Exposing addMethod as queueMethod will allow more powerful derived work.
Should fix https://github.com/yeoman/generator/issues/1112
Example: https://github.com/yeoman/generator/blob/4b4ebde523643c474e586602f0631bce4b36b037/test/base.js#L1180-L1190
The queued function will execute at derived classes:
https://github.com/yeoman/generator/blob/4b4ebde523643c474e586602f0631bce4b36b037/test/base.js#L1207-L1224
=> Expose addMethod

lib/index.js, lib/util/conflicter.js, test/conflicter.js
This option when set to true, we will abort on first conflict. (used for
testing reproducibility)
=> Implement abort option.

lib/index.js, test/generators-compose-workflow.js, test/storage.js
Add a shortcut to call multiple generators on composeWith.
Add a workflow test with multiple generators.
=> Add support to array on composeWith

lib/index.js, lib/util/conflicter.js, package-lock.json, package.json, test/conflicter.js
- Reimplement detect-conflict inline to make it easier to change.
- Add ignore whitespace comparison.
- Add skipRegeneration option to don't override files with whitespace changes.
=> Migrate from detect-conflict to diff (JsDiff)

lib/index.js, lib/util/conflicter.js, test/conflicter.js
Should fix https://github.com/yeoman/environment/issues/110
=> Add dry-run option

lib/index.js
The error is thrown outside the runLoop, so it's not properly emitted.
=> Emit error instead of throwing it.

lib/index.js, test/generators.js
interference.
- Don't look for .yo-rc.json at parent folders.
- Simulate global config at current folder.
Fixes https://github.com/yeoman/generator/issues/1094
=> Implement localConfigOnly option, to reduce unwanted outside

.github/workflows/gh_pages.yml, lib/index.js, test/base.js
- Create queueTask, createTaskGroup methods.
- Add options to custom priorities.
Allows to create custom priorities that executes an task only once (based on the method name).
Useful for inheritance and composability.
=> Improvements to custom priorities

package-lock.json, package.json
v0.8.4 included a commit to prevent circular dependency warnings in Node 14.
See also: https://github.com/shelljs/shelljs/pull/973
=> Bump shelljs to 0.8.4

lib/index.js
Correct cache to store.
Add that storage property can be specified as a string.
Add that storage parameter is a fallback storage.
=> Update description of prompt

lib/index.js, test/base.js
Allows tasks to have a prefix, methods can be treated as normal api.
=> Implement taskPrefix feature.

lib/index.js, test/base.js
Allows composing with another generator, with the composed generator been queued before current one.
An async before queue callback generates an async composeWith().
=> Add before queue callback and composeWith immediately.

package-lock.json, package.json
Snyk has identified a vulnerably dependency `shelljs` in this repository - Can see details here: https://snyk.io/vuln/npm:shelljs
This PR simply bumps the shelljs version from 0.8.4 to 0.8.5 resolving that vulnerability.
=> Bump version of shelljs to avoid vulnerable 0.8.4 version

.github/workflows/ci.yml, .github/workflows/gh_pages.yml, .github/workflows/integration.yml, .github/workflows/lock-maintenance.yml, .github/workflows/stale.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> Set permissions for GitHub actions

package-lock.json, package.json, src/actions/fs.ts, test/fs.test.ts
addresses #1481 
1. Improve readability to make it easier for readers to use tests to understand the generator code / use the tests as specifications
- I created constants to use as array indices so that the intent is explicit.
2. Fix TypeScript problems:  Added, defined types where needed. 
- In order to use ejs `Data` type for templates, had to explicitly include `@types/ejs` and `ejs` in the package.
- `GeneratorOptions` requires `help:` be included; added it to a new Generator.... call where it was missing
- I had to add a `@ts-expect-error` comment for a line where `esmocha.spyOn(...)` is used. I referenced the known GitHub issue.  I added a comment noting that the spyOn could be replaced with a sinonStub(), since the result of the spy is never checked.
I did not squash my commits. I …
=> fs.test.ts: Improve readbility, add types to fix TS problems

package-lock.json, test/deprecate.test.ts
- added TODO for changing `deprecate.js` to `deprecate.ts` (as a reminder and to note which lines can be changed (improved) when that happends
- added types (SinonSpy, a type for the object used for testing)
- created separate tests for:
- testing deprecated functions
- testing deprecated objects
- properties
- functions
- change the word 'wrapped' so that it's clear what is happening (deprecation)
part of cleaning up tests #1481
=> Test cleanup: deprecate.test.ts

test/spawn-command.test.ts
- Added tests for `spawn` and `spawnSync`
- Changed existing tests for `spawnCommand` and `spawnCommandSync`:  they call spawn and spawnSync
- changed the name of the generator used for testing from "spawn" to "testGenerator."  The word "spawn" was used too much (ex: `spawn.spawn(..)` is not very clear)
Part of test cleanup: #1481
=> Test cleanup: spawn command

src/generator.ts
added 'EventEmitter' interface to 'BaseGenerator' explicitly, as the emitter functionality is demanded by 'BaseGenerator' of '@yeoman/types'
=> updated import in 'generator.ts' to be properly resolvable without "allowSyntheticDefaultImports": true in 'tsconfig.json'

src/index.ts
Exports types from `questions.d.ts`.
Fixes #1575
=> chore: Export questions types

src/actions/lifecycle.ts
Workaround https://github.com/nodejs/node/pull/55270
=> fix: replace Duplex with Transform

src/actions/user.ts
Deprecate GitHub/username utility.
This utility has very limited usefulness and it’s dependencies take at least a third of yeoman-generator install size.
=> chore: deprecate github/username utility

package-lock.json, package.json
Move `@types/node` to peer dependencies and make it optional.
So it won't be pulled in prod installs.
`mem-fs-editor` needs the same fix.
=> feat: move `@types/node` to peer dependencies and make it optional.
